spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/pizza1
spring.datasource.username=postgres
#spring.datasource.password=2004
spring.datasource.password=anthony16

spring.jpa.hibernate.ddl-auto=update

# linea pra poderm ostrar las consultas SQL en consola
spring.jpa.show-sql=true